### ISSUE TITLE
Un elenco puntato saltato?

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/Pug#1]
Caro @gbvitrano ,
[qui](https://opendatasicilia.github.io/Pug/cap_04/#43-ambito-strategico-della-rigenerazione-urbana) vedo questo.

È corretto?

![image](https://github.com/opendatasicilia/Pug/assets/30607/1ce54d76-b9ee-421f-a864-0d8f033052fb)

**Comment by gbvitrano** [comment]
controllo :-)

**Comment by cirospat** [comment]
aggiustata formattazione
